print('-', '-', '-', sep='-')
print('|   |')
print('|   |')
print('-', '-', '-', sep='-')
print('     *     ')
print('    * *    ')
print('   *   *    ')
print('  *     *    ')
print(' *********    ')
