print("Programming","Essentials","in", sep='***', end='...')
print("Python")
print("    *\n   * *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *****\n" * 2)
print (3.5E8)
print (6.62607E-34)
print(0.0000000000000000000001)
print ('dut-e sa te \"duci\"')
print ('maria "are" mere')
print ('I\'m Monty Python.')
print ("I'm Monty Python.")
print(True > False)
print(True < False)
print(6%5)
print((5 * ((25 % 13) + 100) / (2 * 13)) // 2)
print((2 ** 4), (2 * 4.), (2 * 4))
print((-2 / 4), (2 / 4), (2 // 4), (-2 // 4))
print((2 % -4), (2 % 4), (2 ** 3 ** 2))
#['False', 'None', 'True', 'and', 'as', 'assert', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
