print('-', '-', '-', sep='-',end='\n')
print('|   |')
print('|   |')
print('-', '-', '-', sep='-',end='\n')
print('     *     ',end='\n')
print('    * *    ',end='\n')
print('   *   *    ',end='\n')
print('  *     *    ',end='\n')
print(' *********    ',end='\n')